
const PRODUTOS = [
  {
    id: 1,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta ColorFlow',
    material: 'Bioplástico vegetal',
    descricao: 'Corpo feito de bioplástico derivado de cana-de-açúcar, com tinta à base de água que seca rápido e não mancha o papel.',
    preco: 14.9,
    estoque: 42,
    avaliacao: 5,
    selo: 'vendido',
    imagem: 'https://images.pexels.com/photos/6969319/pexels-photo-6969319.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 2,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta InkBloom Trio',
    material: 'Fibra de bambu',
    descricao: 'Conjunto com três cores em corpo de bambu certificado, ideal para anotações coloridas sem química agressiva.',
    preco: 29.9,
    estoque: 18,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6969324/pexels-photo-6969324.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 3,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Lapiseira RootWood',
    material: 'Madeira reflorestada',
    descricao: 'Lapiseira 0.7mm com corpo em madeira de reflorestamento manejado, acabamento natural sem verniz sintético.',
    preco: 19.5,
    estoque: 31,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5412374/pexels-photo-5412374.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 4,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta Gel TerraSoft',
    material: 'Plástico oceânico reciclado',
    descricao: 'Gel de escrita suave com corpo feito de plástico recolhido do oceano antes de chegar à costa.',
    preco: 12.9,
    estoque: 55,
    avaliacao: 4,
    selo: 'lancamento',
    imagem: 'https://images.pexels.com/photos/30634315/pexels-photo-30634315.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 5,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Marca-texto FibraViva',
    material: 'Fibra de cana-de-açúcar',
    descricao: 'Ponta chanfrada e tinta fluorescente atóxica, corpo em bioplástico de cana de açúcar.',
    preco: 9.9,
    estoque: 63,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/30633929/pexels-photo-30633929.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 6,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta Esferográfica Origem',
    material: 'Papel reciclado prensado',
    descricao: 'Corpo em papel reciclado prensado a alta pressão, com refil substituível para reduzir descarte.',
    preco: 7.9,
    estoque: 80,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/356340/pexels-photo-356340.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 7,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta Tinteiro Renova',
    material: 'Fibra de bambu',
    descricao: 'Tinteiro clássico com corpo de bambu maciço e cartucho de tinta recarregável.',
    preco: 54.9,
    estoque: 12,
    avaliacao: 5,
    selo: 'lancamento',
    imagem: 'https://images.pexels.com/photos/8716103/pexels-photo-8716103.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 8,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Lápis Ecológico SemFim',
    material: 'Papel reciclado enrolado',
    descricao: 'Grafite envolto em papel reciclado em espiral; não precisa de apontador, vai descascando como rótulo.',
    preco: 6.9,
    estoque: 91,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6969319/pexels-photo-6969319.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 9,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta Roller GreenWrite',
    material: 'Bioplástico vegetal',
    descricao: 'Ponta roller 0.5mm com fluxo constante, corpo em bioplástico compostável em até 180 dias.',
    preco: 16.9,
    estoque: 24,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6969324/pexels-photo-6969324.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 10,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Lápis de Cor Raiz',
    material: 'Madeira reflorestada',
    descricao: 'Caixa com 12 cores feitas de madeira de reflorestamento e pigmentos à base de minerais naturais.',
    preco: 34.9,
    estoque: 27,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5412374/pexels-photo-5412374.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 11,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta Permanente EcoMark',
    material: 'Plástico oceânico reciclado',
    descricao: 'Tinta permanente para etiquetas e superfícies, corpo 100% reciclado pós-consumo.',
    preco: 11.9,
    estoque: 38,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/30634315/pexels-photo-30634315.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 12,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta 3 em 1 Multiverde',
    material: 'Fibra de bambu',
    descricao: 'Caneta, lapiseira e marcador em um único corpo de bambu, prática para mochila escolar.',
    preco: 22.9,
    estoque: 20,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/30633929/pexels-photo-30633929.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 13,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Apontador Compacto Terra',
    material: 'Madeira reflorestada',
    descricao: 'Apontador manual com reservatório, estrutura de madeira certificada e lâmina de aço inox.',
    preco: 8.9,
    estoque: 47,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/356340/pexels-photo-356340.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 14,
    categoria: 'caneta',
    categoriaNome: 'Canetas',
    nome: 'Caneta Brush FlowArt',
    material: 'Bioplástico vegetal',
    descricao: 'Ponta pincel flexível para lettering, tinta à base de água em corpo biodegradável.',
    preco: 13.9,
    estoque: 33,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/8716103/pexels-photo-8716103.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 15,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno EcoBook 200 Folhas',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Capa dura revestida em papel kraft reciclado, 200 folhas certificadas FSC com pauta suave.',
    preco: 39.9,
    estoque: 18,
    avaliacao: 5,
    selo: 'lancamento',
    imagem: 'https://images.pexels.com/photos/5088017/pexels-photo-5088017.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 16,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno Pontilhado Origem',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Ideal para bullet journal, papel reciclado de gramatura alta que não vaza com canetas finas.',
    preco: 44.9,
    estoque: 14,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5088008/pexels-photo-5088008.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 17,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Agenda Permanente Renova',
    material: 'Papel semente',
    descricao: 'Sem datas fixas, pode ser usada em qualquer ano. Capa feita de papel semente: depois de usada, pode ser plantada.',
    preco: 49.9,
    estoque: 9,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/7718714/pexels-photo-7718714.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 18,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno Universitário FibraNote',
    material: 'Fibra de bambu',
    descricao: '10 matérias com divisórias, capa em compósito de fibra de bambu resistente à umidade.',
    preco: 32.9,
    estoque: 25,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5208820/pexels-photo-5208820.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 19,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Bloco de Notas TerraPages',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Bloco destacável de 80 folhas, ótimo para recados e listas rápidas sem desperdício.',
    preco: 11.9,
    estoque: 60,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/604575/pexels-photo-604575.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 20,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Sketchbook RaizArte',
    material: 'Algodão orgânico',
    descricao: 'Papel com 30% de algodão orgânico, textura ideal para grafite e nanquim sem transparência.',
    preco: 58.9,
    estoque: 11,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/434337/pexels-photo-434337.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 21,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno Inteligente VerdeNote',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Folhas soltas com sistema de discos recicláveis, permite reorganizar e reutilizar a capa.',
    preco: 62.9,
    estoque: 8,
    avaliacao: 5,
    selo: 'lancamento',
    imagem: 'https://images.pexels.com/photos/8059290/pexels-photo-8059290.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 22,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Mini Caderno de Bolso Folha',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Formato compacto para carteira ou estojo, 60 folhas para anotações do dia a dia.',
    preco: 9.9,
    estoque: 74,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5088017/pexels-photo-5088017.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 23,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Planner Semanal Cultiva',
    material: 'Papel semente',
    descricao: 'Planejamento semanal sem ano impresso, capa de papel semente germinável após o uso.',
    preco: 46.9,
    estoque: 16,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5088008/pexels-photo-5088008.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 24,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno de Receitas Raiz',
    material: 'Fibra de bambu',
    descricao: 'Divisórias temáticas para organizar receitas, capa resistente a respingos de cozinha.',
    preco: 36.9,
    estoque: 13,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/7718714/pexels-photo-7718714.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 25,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Diário Reflexo Terra',
    material: 'Algodão orgânico',
    descricao: 'Páginas em papel de algodão orgânico com perguntas guiadas para escrita diária.',
    preco: 41.9,
    estoque: 17,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/5208820/pexels-photo-5208820.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 26,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno Escolar EcoTurma',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Pacote com capa colorida atóxica, indicado para uso escolar do ensino fundamental.',
    preco: 15.9,
    estoque: 120,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/604575/pexels-photo-604575.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 27,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Caderno de Viagem Trilha',
    material: 'Fibra de bambu',
    descricao: 'Elástico de fechamento, porta-cartão interno e capa resistente para uso em mochilas.',
    preco: 52.9,
    estoque: 10,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/434337/pexels-photo-434337.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 28,
    categoria: 'caderno',
    categoriaNome: 'Cadernos',
    nome: 'Bloco Adesivo Memo Verde',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Conjunto de blocos adesivos coloridos com adesivo à base de látex natural.',
    preco: 13.9,
    estoque: 58,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/8059290/pexels-photo-8059290.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 29,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Post-it Nature',
    material: 'Fibra natural sustentável',
    descricao: 'Bloco de notas adesivas em papel de fibra natural, cola à base de látex vegetal.',
    preco: 10.9,
    estoque: 27,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/8386701/pexels-photo-8386701.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 30,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Clipes OrganizaEco',
    material: 'Plástico oceânico reciclado',
    descricao: 'Caixa com 100 clipes coloridos feitos a partir de plástico recolhido do mar.',
    preco: 8.9,
    estoque: 70,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/1629212/pexels-photo-1629212.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 31,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Fita Adesiva FitaTerra',
    material: 'Papel kraft reciclado',
    descricao: 'Fita decorativa em papel kraft com adesivo removível, não deixa resíduo na parede.',
    preco: 7.9,
    estoque: 85,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6183/pexels-photo-6183.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 32,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Pasta Sanfonada PastaRenova',
    material: 'Papel reciclado certificado FSC',
    descricao: '12 divisórias para documentos, estrutura reforçada em papelão reciclado prensado.',
    preco: 24.9,
    estoque: 22,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/927576/pexels-photo-927576.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 33,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Caixa Organizadora CaixaFibra',
    material: 'Fibra de bambu',
    descricao: 'Caixa modular empilhável feita de compósito de fibra de bambu, ótima para mesa de estudos.',
    preco: 38.9,
    estoque: 15,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6368842/pexels-photo-6368842.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 34,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Marcador de Página MarcaEco',
    material: 'Cortiça natural',
    descricao: 'Conjunto com 5 marcadores em cortiça natural, leves e sem química de tingimento.',
    preco: 12.9,
    estoque: 40,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/8386701/pexels-photo-8386701.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 35,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Etiquetas Adesivas EtiquetaViva',
    material: 'Papel kraft reciclado',
    descricao: 'Folhas de etiquetas para organização de potes e arquivos, impressão compatível com impressoras comuns.',
    preco: 9.9,
    estoque: 66,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/1629212/pexels-photo-1629212.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 36,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Organizador de Mesa OrganizFolha',
    material: 'Fibra de bambu',
    descricao: 'Porta-canetas e acessórios com compartimentos, estrutura sólida de bambu prensado.',
    preco: 45.9,
    estoque: 12,
    avaliacao: 5,
    selo: 'lancamento',
    imagem: 'https://images.pexels.com/photos/6183/pexels-photo-6183.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 37,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Separadores SeparaVerde',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Conjunto de separadores coloridos para fichários, indicado para organização por matéria ou projeto.',
    preco: 11.9,
    estoque: 48,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/927576/pexels-photo-927576.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 38,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Pasta Arquivo ArquivoEco',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Pasta com elástico para guardar documentos importantes, capa resistente à umidade leve.',
    preco: 19.9,
    estoque: 34,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6368842/pexels-photo-6368842.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 39,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Porta-Lápis PortaTerra',
    material: 'Cortiça natural',
    descricao: 'Porta-lápis cilíndrico em cortiça natural prensada, base antiderrapante de fibra reciclada.',
    preco: 21.9,
    estoque: 29,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/8386701/pexels-photo-8386701.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 40,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Grampeador GrampoVerde',
    material: 'Plástico oceânico reciclado',
    descricao: 'Grampeador compacto sem necessidade de grampos metálicos, usa corte e dobra do próprio papel.',
    preco: 27.9,
    estoque: 19,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/1629212/pexels-photo-1629212.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 41,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Fichário FichaRenova',
    material: 'Papel reciclado certificado FSC',
    descricao: 'Fichário de argolas com capa em papel reciclado rígido e folhas de reposição disponíveis.',
    preco: 33.9,
    estoque: 21,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/6183/pexels-photo-6183.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 42,
    categoria: 'organizacao',
    categoriaNome: 'Organização',
    nome: 'Quadro de Avisos QuadroFibra',
    material: 'Fibra de bambu',
    descricao: 'Quadro de avisos com moldura de bambu e superfície de cortiça para fixar lembretes.',
    preco: 59.9,
    estoque: 7,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/927576/pexels-photo-927576.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 43,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Aquarela ArteViva',
    material: 'Pigmentos minerais naturais',
    descricao: 'Conjunto com 24 cores em pastilha, pigmentos de origem mineral sem metais pesados.',
    preco: 48.9,
    estoque: 16,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/3777878/pexels-photo-3777878.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 44,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Pincel PincelEco',
    material: 'Madeira reflorestada',
    descricao: 'Kit com 5 pincéis de cerdas sintéticas e cabo em madeira de reflorestamento certificado.',
    preco: 31.9,
    estoque: 23,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/10474187/pexels-photo-10474187.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 45,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Giz de Cera GizFolha',
    material: 'Cera de soja',
    descricao: 'Giz de cera feito com cera de soja em vez de parafina, cores vibrantes e atóxicas.',
    preco: 17.9,
    estoque: 50,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/7885377/pexels-photo-7885377.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 46,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Lápis Aquarelável LápisRaiz',
    material: 'Madeira reflorestada',
    descricao: 'Conjunto de 18 lápis aquareláveis com corpo em madeira de reflorestamento manejado.',
    preco: 42.9,
    estoque: 18,
    avaliacao: 5,
    selo: 'lancamento',
    imagem: 'https://images.pexels.com/photos/16698511/pexels-photo-16698511.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 47,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Paleta de Tintas PaletaEco',
    material: 'Pigmentos minerais naturais',
    descricao: 'Tintas guache à base de pigmentos minerais, frascos recarregáveis para reduzir descarte plástico.',
    preco: 36.9,
    estoque: 20,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/3777878/pexels-photo-3777878.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 48,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Carvão Artístico CarvãoNature',
    material: 'Madeira reflorestada',
    descricao: 'Bastões de carvão vegetal produzidos a partir de poda de árvores certificadas.',
    preco: 14.9,
    estoque: 35,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/10474187/pexels-photo-10474187.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 49,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Marcador Artístico MarcadorVerde',
    material: 'Bioplástico vegetal',
    descricao: 'Marcadores de ponta dupla para ilustração, tinta à base de água e corpo biodegradável.',
    preco: 26.9,
    estoque: 28,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/7885377/pexels-photo-7885377.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 50,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Tela para Pintura TelaEco',
    material: 'Algodão orgânico',
    descricao: 'Tela montada em algodão orgânico cru, ideal para acrílico e óleo sobre chassi de madeira certificada.',
    preco: 54.9,
    estoque: 9,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/16698511/pexels-photo-16698511.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 51,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Esponjas de Textura EsponjaTerra',
    material: 'Fibra de cana-de-açúcar',
    descricao: 'Conjunto de esponjas para técnicas de textura em pintura, material 100% biodegradável.',
    preco: 13.9,
    estoque: 44,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/3777878/pexels-photo-3777878.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 52,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Canetinhas CanetinhaViva',
    material: 'Bioplástico vegetal',
    descricao: 'Caixa com 24 canetinhas hidrográficas laváveis, corpo em bioplástico compostável.',
    preco: 29.9,
    estoque: 37,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/10474187/pexels-photo-10474187.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 53,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Crayon Orgânico CrayonFolha',
    material: 'Cera de soja',
    descricao: 'Crayons em formato triangular antiderrapante, feitos de cera de soja com pigmento vegetal.',
    preco: 18.9,
    estoque: 41,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/7885377/pexels-photo-7885377.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 54,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Pastel Seco PastelEco',
    material: 'Pigmentos minerais naturais',
    descricao: 'Conjunto de pastéis secos para desenho artístico, pigmentação mineral de alta cobertura.',
    preco: 39.9,
    estoque: 15,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/16698511/pexels-photo-16698511.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 55,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Papel para Algodão AlgodãoArt',
    material: 'Algodão orgânico',
    descricao: 'Bloco de papel 100% algodão orgânico para aquarela, gramatura 300g resistente à água.',
    preco: 47.9,
    estoque: 12,
    avaliacao: 5,
    selo: null,
    imagem: 'https://images.pexels.com/photos/3777878/pexels-photo-3777878.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
  {
    id: 56,
    categoria: 'arte',
    categoriaNome: 'Arte',
    nome: 'Estojo de Pincéis FibraPincel',
    material: 'Fibra de bambu',
    descricao: 'Estojo enrolável em fibra de bambu trançada para guardar e transportar pincéis com segurança.',
    preco: 24.9,
    estoque: 26,
    avaliacao: 4,
    selo: null,
    imagem: 'https://images.pexels.com/photos/10474187/pexels-photo-10474187.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop'
  },
];